apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- clusterrole-attacher.yaml
- clusterrole-csi-node.yaml
- clusterrole-provisioner.yaml
- clusterrole-resizer.yaml
- clusterrole-snapshotter.yaml
- clusterrolebinding-attacher.yaml
- clusterrolebinding-csi-node.yaml
- clusterrolebinding-provisioner.yaml
- clusterrolebinding-resizer.yaml
- clusterrolebinding-snapshotter.yaml
- controller.yaml
- csidriver.yaml
- node.yaml
- poddisruptionbudget-controller.yaml
- serviceaccount-csi-controller.yaml
- serviceaccount-csi-node.yaml
- role-leases.yaml
- rolebinding-leases.yaml
