apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../ecr-public
images:
  - name: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver
    newName: registry.k8s.io/provider-aws/aws-ebs-csi-driver
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newName: registry.k8s.io/sig-storage/csi-provisioner
    newTag: v4.0.0
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-attacher
    newName: registry.k8s.io/sig-storage/csi-attacher
    newTag: v4.5.0
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newName: registry.k8s.io/sig-storage/livenessprobe
    newTag: v2.12.0
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter
    newName: registry.k8s.io/sig-storage/csi-snapshotter
    newTag: v7.0.0
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-resizer
    newName: registry.k8s.io/sig-storage/csi-resizer
    newTag: v1.10.0
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newName: registry.k8s.io/sig-storage/csi-node-driver-registrar
    newTag: v2.10.0
