apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
images:
  - name: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
    newTag: v1.12.0
  - name: k8s.gcr.io/sig-storage/csi-attacher
    newTag: v3.4.0
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newTag: v2.5.1
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newTag: v3.1.0
  - name: k8s.gcr.io/sig-storage/csi-resizer
    newTag: v1.4.0
  - name: k8s.gcr.io/sig-storage/csi-snapshotter
    newTag: v6.0.1
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newTag: v2.6.0
