apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../ecr-public
images:
  - name: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-attacher
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-attacher
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-snapshotter
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-resizer
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar
