apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../gcr
images:
  - name: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver
    newTag: v1.5.0
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner
  - name: k8s.gcr.io/sig-storage/csi-attacher
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-attacher
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe
  - name: k8s.gcr.io/sig-storage/csi-snapshotter
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-snapshotter
  - name: k8s.gcr.io/sig-storage/csi-resizer
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar
