name: Container Images

on:
  push:

jobs:
  buildx:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'kubernetes-sigs/aws-ebs-csi-driver'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set environment variables
        run: |
          REGISTRY_NAME=docker.io/library/amazon
          BRANCH_OR_TAG=$(echo $GITHUB_REF | cut -d'/' -f3)
          if [ "$BRANCH_OR_TAG" = "master" ]; then
            GIT_TAG=$GITHUB_SHA
          else
            GIT_TAG=$BRANCH_OR_TAG
          fi
          echo "REGISTRY_NAME=$REGISTRY_NAME" >> $GITHUB_ENV
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push manifest list containing amazon linux and windows based images to Docker Hub
        run: |
          export REGISTRY=$REGISTRY_NAME
          export TAG=$GIT_TAG
          make all-push
